name: Create Netlify deploy preview links
on:
  pull_request:
    paths:
      - 'dev/**/*.html'
      - 'dev/**/*.htm'
jobs:
  create-deploy-preview-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Post a list of Netlify preview URLs to the opened pull request
        run: |
          git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
