name: Create Netlify deploy preview links
on:
  pull_request:
    paths:
      - 'dev/**/*.html'
      - 'dev/**/*.htm'
jobs:
  create-deploy-preview-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Post a list of Netlify preview URLs to the opened pull request
        run: |
          FILE_CMD='git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E "^dev.*\.html?$"'
          STRIP_CMD='sed "sed "s/^dev//g"'
          eval $FILE_CMD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
